AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Alexa Music Skill API エンドポイント"

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    MemorySize: 256

Resources:
  AlexaMusicSkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: alexa-mp3-music-skill
      Handler: dist/index.handler
      Architectures:
        - arm64
      CodeUri: .
      Environment:
        Variables:
          PARTYKIT_URL: !Ref PartyKitUrl
          API_SECRET: !Ref ApiSecret
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill

Parameters:
  PartyKitUrl:
    Type: String
    Description: "PartyKitのデプロイ先URL"
    Default: ""
  ApiSecret:
    Type: String
    Description: "PartyKit-Lambda間の認証秘密鍵"
    NoEcho: true
    Default: ""

Outputs:
  FunctionArn:
    Description: "Lambda関数のARN（Alexa開発者コンソールに設定する値）"
    Value: !GetAtt AlexaMusicSkillFunction.Arn
